#server:
#  port: 8888
#spring:
#  application:
#    name: configserver
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:///home/raj/Desktop/config
#          default-label: main
          #clone-on-start: true

#spring.cloud.config.server.git.default-label=master
