#spring:
#  application:
#    name: config-client
#  config:
#    import: "configserver:http://localhost:8888"
#server:
#  port: 8080

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*""