##management.endpoints.web.exposure.include=*
##spring.config.import=configserver:http://localhost:8888
###spring.application.name=client-app
##management.endpoints.web.exposure.exclude=*
#
##spring.application.name=configserver
##spring.cloud.config.server.git.uri=file://home/raj/Desktop/config
###spring.cloud.config.server.git.clone-on-start=true
##server.port=8888
##spring.cloud.config.server.git.default-label=master
#
#spring.application.name=configserver
#spring.cloud.config.server.git.uri

management:
  endpoints:
    web:
      exposure:
        exclude: *

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        uri: file://home/raj/Desktop/config
      git:
        clone-on-start: true
        default-label: master
        