server:
  port: 8090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: weatherservice
          uri: lb://WEATHER-SERVICE
          predicates:
            - Path=/weatherservice/**
        - id: weatherclient
          uri: lb://WEATHER-CLIENT
          predicates:
            - Path=/weatherclient/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
